# CAISO DATA Collection and Preparation

The [CAISO website](http://www.caiso.com/Pages/default.aspx) provides access to real-time data on California's energy supply and demand, as well as CO2 emissions.  The [Today's Outlook page](http://www.caiso.com/TodaysOutlook/Pages/index.html) is a very polished presentation of data that interests the public and energy and climate watchers but it is presented from a particular viewpoint that prioritizes so-called "renewable" sources.  This analysis is intended to show the data from a low-carbon/high-carbon viewpoint.

This notebook summarizes the code used to collect and aggregate data from [CAISO's Today's Outlook page](http://www.caiso.com/TodaysOutlook/Pages/index.html).  Although CAISO provides access to the backend data through its [OASIS platform](http://oasis.caiso.com/mrioasis/logon.do), that data is not in a form that is easily analyzed by those like me who are not energy market financial analysts.  It would be wonderful if CAISO provided instructions for how they extract and aggregate the data to present their public-facing "Today's Outlook" page so that this method would not be necessary...

In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd
import os
import datetime
import time
import glob #glob has a function that can turn the wildcard into a list of filenames

# Demand Scraping

In [ ]:
driver = webdriver.Chrome()
driver.get('https://www.caiso.com/TodaysOutlook/Pages/index.html')
demanddate = driver.find_element(By.CLASS_NAME, "form-control.form-control-sm.date.demand-date")

In [ ]:
#Note: This will download TODAY's DEMAND
#driver.execute_script("el = document.querySelector('#downloadDemandCSV');el.click();")

In [ ]:
#Loop through the dates we want data from
startdate = datetime.date(2022,1,1)
enddate = datetime.date(2022,8,8)
diff = enddate - startdate

indir = "/Users/jklay/Downloads/"
outdir = "/Users/jklay/energyanalysis/data/"

In [ ]:
for i in range(diff.days + 1):
    today = startdate + datetime.timedelta(i)
    caisodate = today.strftime("%m/%d/%Y")
    csvdate = today.strftime("%Y%m%d")
    print ("Processing:",caisodate," ",csvdate)
    demanddate.clear()
    demanddate.send_keys(caisodate)
    demanddate.send_keys(Keys.ENTER)
    downloadmenu = driver.find_element(By.ID, "dropdownMenu1");
    downloadmenu.click()
    chartcsv = driver.find_element(By.CLASS_NAME, "dropdown-item");
    chartcsv.click()
    time.sleep(5) #avoid file-not-found due to slow download
    infile = f"{indir}CAISO-demand-{csvdate}.csv"
    outfile = f"{outdir}CAISO-demand-{csvdate}.csv"
    os.rename(infile, outfile)

In [ ]:
#Read in a csv file as Pandas dataframe
test = pd.read_csv(outfile)
print(test)

# Supply Scraping

In [ ]:
driver = webdriver.Chrome()
driver.get('https://www.caiso.com/TodaysOutlook/Pages/supply.html')
supplydate = driver.find_element(By.CLASS_NAME, "form-control.form-control-sm.date.supply-trend-date")

In [ ]:
#Loop through the dates we want data from
startdate = datetime.date(2022,1,1)
enddate = datetime.date(2022,8,8)
diff = enddate - startdate

indir = "/Users/jklay/Downloads/"
outdir = "/Users/jklay/energyanalysis/data/"

In [ ]:
for i in range(diff.days + 1):
    today = startdate + datetime.timedelta(i)
    caisodate = today.strftime("%m/%d/%Y")
    csvdate = today.strftime("%Y%m%d")
    print ("Processing:",caisodate," ",csvdate)
    supplydate.clear()
    supplydate.send_keys(caisodate)
    supplydate.send_keys(Keys.ENTER)
    downloadmenu = driver.find_element(By.ID, "dropdownMenuSupplyDownload");
    downloadmenu.click()
    chartcsv = driver.find_element(By.CLASS_NAME, "dropdown-item");
    chartcsv.click()
    time.sleep(5) #avoid file-not-found due to slow download
    infile = f"{indir}CAISO-supply-{csvdate}.csv"
    outfile = f"{outdir}CAISO-supply-{csvdate}.csv"
    os.rename(infile, outfile)

# Renewables Scraping

In [ ]:
driver = webdriver.Chrome()
driver.get('https://www.caiso.com/TodaysOutlook/Pages/supply.html')
renewdate = driver.find_element(By.CLASS_NAME, "form-control.form-control-sm.date.renewables-date")

In [ ]:
#Loop through the dates we want data from
startdate = datetime.date(2022,1,1)
enddate = datetime.date(2022,8,8)
diff = enddate - startdate

indir = "/Users/jklay/Downloads/"
outdir = "/Users/jklay/energyanalysis/data/"

In [ ]:
for i in range(diff.days + 1):
    today = startdate + datetime.timedelta(i)
    caisodate = today.strftime("%m/%d/%Y")
    csvdate = today.strftime("%Y%m%d")
    print ("Processing:",caisodate," ",csvdate)
    renewdate.clear()
    renewdate.send_keys(caisodate)
    renewdate.send_keys(Keys.ENTER)
    downloadmenu = driver.find_element(By.ID, "dropdownMenuRenewables");
    downloadmenu.click()
    chartcsv = driver.find_element(By.CLASS_NAME, "dropdown-item.mb-0");
    chartcsv.click()
    time.sleep(5) #avoid file-not-found due to slow download
    infile = f"{indir}CAISO-renewables-{csvdate}.csv"
    outfile = f"{outdir}CAISO-renewables-{csvdate}.csv"
    os.rename(infile, outfile)

# Emissions Scraping

In [ ]:
driver = webdriver.Chrome()
driver.get('https://www.caiso.com/TodaysOutlook/Pages/emissions.html')
co2date = driver.find_element(By.CLASS_NAME, "form-control.form-control-sm.date.co2-breakdown-date")

In [ ]:
#Loop through the dates we want data from
startdate = datetime.date(2022,1,1)
enddate = datetime.date(2022,8,8)
diff = enddate - startdate

indir = "/Users/jklay/Downloads/"
outdir = "/Users/jklay/energyanalysis/data/"

In [ ]:
for i in range(diff.days + 1):
    today = startdate + datetime.timedelta(i)
    caisodate = today.strftime("%m/%d/%Y")
    csvdate = today.strftime("%Y%m%d")
    print ("Processing:",caisodate," ",csvdate)
    co2date.clear()
    co2date.send_keys(caisodate)
    co2date.send_keys(Keys.ENTER)
    downloadmenu = driver.find_element(By.ID, "dropdownMenuCO2Breakdown");
    downloadmenu.click()
    chartcsv = driver.find_element(By.ID, "downloadCO2BreakdownCSV");
    chartcsv.click()
    time.sleep(5) #avoid file-not-found due to slow download
    infile = f"{indir}CAISO-co2-per-resource-{csvdate}.csv"
    outfile = f"{outdir}CAISO-co2-per-resource-{csvdate}.csv"
    os.rename(infile, outfile)

# Aggregate Demand Data

In [2]:
def process_demand_files(f):
    newdf = pd.read_csv(f)
    date = newdf.columns.tolist()[0].split()[1]
    newdf.drop([0,1,3],inplace=True) #rows
    newdf.insert(0, "Date", date, True)
    newdf.columns.values[1] = "Type"
    newdf.drop(columns=['00:00.1'],inplace=True) #last column is only in demand data
    newdf.fillna(0) #replace any null entries with 0
    return newdf

In [3]:
file_location = os.path.join('data','*demand*.csv')
filenames = sorted(glob.glob(file_location))

In [4]:
frames = [ process_demand_files(f) for f in filenames ]
result = pd.concat(frames)
result.reset_index(drop=True,inplace=True)

In [5]:
result.to_csv("CAISO-demand-2022.csv",index=False)

In [7]:
result
result.isnull().sum().sum()

16

# Aggregate Supply Data

In [106]:
f = ['data/CAISO-supply-20220101.csv']
#NOTE: Their supply data has a different format for the time column headers than the renewables data

In [107]:
def process_supply_files(f):
    newdf = pd.read_csv(f)
    date = newdf.columns.tolist()[0].split()[1]
    newdf.drop([0],inplace=True) #get rid of "renewables" row
    newdf.drop(newdf.columns[len(newdf.columns)-1], axis=1, inplace=True)
    newdf.insert(0, "Date", date, True)
    newdf.columns.values[1] = "Type"
    newdf.fillna(0) #replace any null entries with 0
    return newdf

In [108]:
file_location = os.path.join('data','*supply*.csv')
filenames = sorted(glob.glob(file_location))

In [109]:
frames = [ process_supply_files(f) for f in filenames ]
result = pd.concat(frames)
result.reset_index(drop=True,inplace=True)

In [110]:
#NOTE: Their supply data has a different format for the time column headers than the renewables data
#Better to fix it here
for i in range(120):
    before = result.columns[i+2]
    after = f"0{before}"
    result.columns.values[i+2] = after
    #print(before,after)
result.to_csv("CAISO-supply-2022.csv",index=False)

In [111]:
result
#result.isnull().sum().sum()

,Date,Type,00:00,00:05,00:10,00:15,00:20,00:25,00:30,00:35,...,23:10,23:15,23:20,23:25,23:30,23:35,23:40,23:45,23:50,23:55
0,01/01/2022,Natural gas,7280,7119,6904,6870,6860,6868,6831,6917,...,10001,9981,9838,9792,9823,9880,9907,9983,9961.0,9941.0
1,01/01/2022,Large hydro,1200,1129,1114,1135,1102,1097,1085,1089,...,1180,1183,1176,1230,1312,1321,1306,1297,1291.0,1280.0
2,01/01/2022,Imports,8200,8079,8085,7962,7973,7889,7822,7890,...,7814,7735,7811,7794,7674,7483,7400,7384,7218.0,7271.0
3,01/01/2022,Batteries,-116,117,149,164,152,147,116,-13,...,52,38,5,1,-53,-18,-77,-130,-57.0,-130.0
4,01/01/2022,Nuclear,2264,2265,2264,2265,2265,2264,2265,2264,...,2265,2265,2265,2265,2266,2265,2264,2265,2265.0,2265.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1535,08/08/2022,Imports,7239,7107,6909,6839,6844,6829,6745,6674,...,6704,6764,6637,6606,6599,6715,6738,6913,6906.0,6935.0
1536,08/08/2022,Batteries,-218,27,299,229,156,88,61,-24,...,-289,-55,79,45,35,-30,-174,-216,-244.0,-276.0
1537,08/08/2022,Nuclear,2263,2263,2263,2264,2263,2264,2264,2264,...,2263,2264,2264,2264,2264,2263,2264,2264,2264.0,2263.0
1538,08/08/2022,Coal,15,16,15,15,15,15,15,16,...,16,15,15,15,15,15,15,15,15.0,15.0
1539,08/08/2022,Other,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.0,0.0

# Aggregate Renewables Data

In [90]:
f = ['data/CAISO-renewables-20220101.csv']

In [91]:
def process_renewables_files(f):
    newdf = pd.read_csv(f)
    date = newdf.columns.tolist()[0].split()[1]
    newdf.insert(0, "Date", date, True)
    newdf.columns.values[1] = "Type"
    newdf.fillna(0) #replace any null entries with 0
    return newdf

In [92]:
file_location = os.path.join('data','*renewables*.csv')
filenames = sorted(glob.glob(file_location))

In [93]:
frames = [ process_renewables_files(f) for f in filenames ]
result = pd.concat(frames)
result.reset_index(drop=True,inplace=True)

In [94]:
print(result.columns[24])

01:50

In [95]:
result.to_csv("CAISO-renewables-2022.csv",index=False)

In [96]:
result
result.isnull().sum().sum()

180

# Aggregate Emissions Data

In [20]:
f = ['data/CAISO-co2-per-resource-20220101.csv']

In [21]:
def process_emissions_files(f):
    newdf = pd.read_csv(f)
    date = newdf.columns.tolist()[0]
    newdf.insert(0, "Date", date, True)
    newdf.columns.values[1] = "Type"
    newdf.fillna(0) #replace any null entries with 0
    return newdf

In [22]:
file_location = os.path.join('data','*co2-per-resource*.csv')
filenames = sorted(glob.glob(file_location))

In [23]:
frames = [ process_emissions_files(f) for f in filenames ]
result = pd.concat(frames)
result.reset_index(drop=True,inplace=True)

In [24]:
result.to_csv("CAISO-co2-per-resource-2022.csv",index=False)

In [25]:
result
result.isnull().sum().sum()

168

# Combine supply sources into one file

In [126]:
def process_allsupply_files(f):
    newdf = pd.read_csv(f)
    newdf.fillna(0) #replace any null entries with 0
    return newdf

In [129]:
filenames = ['CAISO-supply-2022.csv','CAISO-renewables-2022.csv']
frames = [ process_allsupply_files(f) for f in filenames ]
result = pd.concat(frames)
result.sort_values(by=['Date','Type'],ascending=[True,True],inplace=True)
result.reset_index(drop=True,inplace=True)

result.to_csv("CAISO-allsupply-2022.csv",index=False)

In [130]:
result[0:26]

,Date,Type,00:00,00:05,00:10,00:15,00:20,00:25,00:30,00:35,...,23:10,23:15,23:20,23:25,23:30,23:35,23:40,23:45,23:50,23:55
0,01/01/2022,Batteries,-116,117,149,164,152,147,116,-13,...,52,38,5,1,-53,-18,-77,-130,-57.0,-130.0
1,01/01/2022,Biogas,205,208,209,210,211,211,211,211,...,207,207,207,207,207,206,206,207,207.0,207.0
2,01/01/2022,Biomass,281,279,276,273,275,275,272,273,...,291,293,296,292,292,292,292,294,291.0,296.0
3,01/01/2022,Coal,20,20,20,21,20,20,20,19,...,17,17,17,17,18,18,18,18,17.0,18.0
4,01/01/2022,Geothermal,882,880,880,879,879,879,878,878,...,879,879,880,879,880,879,880,880,879.0,879.0
5,01/01/2022,Imports,8200,8079,8085,7962,7973,7889,7822,7890,...,7814,7735,7811,7794,7674,7483,7400,7384,7218.0,7271.0
6,01/01/2022,Large hydro,1200,1129,1114,1135,1102,1097,1085,1089,...,1180,1183,1176,1230,1312,1321,1306,1297,1291.0,1280.0
7,01/01/2022,Natural gas,7280,7119,6904,6870,6860,6868,6831,6917,...,10001,9981,9838,9792,9823,9880,9907,9983,9961.0,9941.0
8,01/01/2022,Nuclear,2264,2265,2264,2265,2265,2264,2265,2264,...,2265,2265,2265,2265,2266,2265,2264,2265,2265.0,2265.0
9,01/01/2022,Other,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.0,0.0
10,01/01/2022,Small hydro,146,144,144,145,144,144,144,144,...,195,194,194,194,194,194,195,195,194.0,179.0
11,01/01/2022,Solar,-32,-32,-32,-32,-32,-32,-32,-32,...,-43,-43,-43,-43,-43,-42,-43,-43,-43.0,-43.0
12,01/01/2022,Wind,3829,3854,3934,4007,3998,4020,4039,3996,...,1086,1135,1154,1180,1170,1134,1108,1082,1079.0,1047.0
13,01/02/2022,Batteries,-116,117,149,164,152,147,116,-13,...,52,38,5,1,-53,-18,-77,-130,-57.0,-130.0
14,01/02/2022,Biogas,205,208,209,210,211,211,211,211,...,207,207,207,207,207,206,206,207,207.0,207.0
15,01/02/2022,Biomass,281,279,276,273,275,275,272,273,...,291,293,296,292,292,292,292,294,291.0,296.0
16,01/02/2022,Coal,20,20,20,21,20,20,20,19,...,17,17,17,17,18,18,18,18,17.0,18.0
17,01/02/2022,Geothermal,882,880,880,879,879,879,878,878,...,879,879,880,879,880,879,880,880,879.0,879.0
18,01/02/2022,Imports,8200,8079,8085,7962,7973,7889,7822,7890,...,7814,7735,7811,7794,7674,7483,7400,7384,7218.0,7271.0
19,01/02/2022,Large hydro,1200,1129,1114,1135,1102,1097,1085,1089,...,1180,1183,1176,1230,1312,1321,1306,1297,1291.0,1280.0
20,01/02/2022,Natural gas,7280,7119,6904,6870,6860,6868,6831,6917,...,10001,9981,9838,9792,9823,9880,9907,9983,9961.0,9941.0
21,01/02/2022,Nuclear,2264,2265,2264,2265,2265,2264,2265,2264,...,2265,2265,2265,2265,2266,2265,2264,2265,2265.0,2265.0
22,01/02/2022,Other,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.0,0.0
23,01/02/2022,Small hydro,146,144,144,145,144,144,144,144,...,195,194,194,194,194,194,195,195,194.0,179.0
24,01/02/2022,Solar,-32,-32,-32,-32,-32,-32,-32,-32,...,-43,-43,-43,-43,-43,-42,-43,-43,-43.0,-43.0
25,01/02/2022,Wind,3829,3854,3934,4007,3998,4020,4039,3996,...,1086,1135,1154,1180,1170,1134,1108,1082,1079.0,1047.0

# Create Low-Carbon/High-Carbon Data Set

In [190]:
demdf = pd.read_csv('CAISO-demand-2022.csv')
demdf.set_index('Date', inplace=True)
alldf = pd.read_csv('CAISO-allsupply-2022.csv')
alldf.set_index('Type', inplace=True)

In [191]:
highcarbon=(alldf.loc[['Biogas','Biomass','Coal','Imports','Natural gas','Other']]).groupby(['Date']).sum()
lowcarbon=(alldf.loc[['Batteries','Geothermal','Large hydro','Nuclear','Small hydro','Solar','Wind']]).groupby(['Date']).sum()

In [192]:
lowcarbon.insert(0, "Type", 'Low Carbon', True)
highcarbon.insert(0, "Type", 'High Carbon', True)

In [195]:
result = pd.concat([lowcarbon,highcarbon,demdf])
result.sort_values(by=['Date','Type'],ascending=[True,True],inplace=True)

result.to_csv("CAISO-NewData-2022.csv")

In [196]:
result

,Type,00:00,00:05,00:10,00:15,00:20,00:25,00:30,00:35,00:40,...,23:10,23:15,23:20,23:25,23:30,23:35,23:40,23:45,23:50,23:55
Date,,,,,,,,,,,,,,,,,,,,,
01/01/2022,Demand,22583.0,22496.0,22429.0,22350.0,22289.0,22198.0,22101.0,22019.0,21951.0,...,23333.0,23209.0,23088.0,22983.0,22893.0,22781.0,22670.0,22580.0,22500.0,22389.0
01/01/2022,High Carbon,15986.0,15705.0,15494.0,15336.0,15339.0,15263.0,15156.0,15310.0,15344.0,...,18330.0,18233.0,18169.0,18102.0,18014.0,17879.0,17823.0,17886.0,17694.0,17733.0
01/01/2022,Low Carbon,8173.0,8357.0,8453.0,8563.0,8508.0,8519.0,8495.0,8326.0,8287.0,...,5614.0,5651.0,5631.0,5706.0,5726.0,5733.0,5633.0,5546.0,5608.0,5477.0
01/02/2022,Demand,22583.0,22496.0,22429.0,22350.0,22289.0,22198.0,22101.0,22019.0,21951.0,...,23333.0,23209.0,23088.0,22983.0,22893.0,22781.0,22670.0,22580.0,22500.0,22389.0
01/02/2022,High Carbon,15986.0,15705.0,15494.0,15336.0,15339.0,15263.0,15156.0,15310.0,15344.0,...,18330.0,18233.0,18169.0,18102.0,18014.0,17879.0,17823.0,17886.0,17694.0,17733.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
08/07/2022,High Carbon,20494.0,20400.0,20709.0,20645.0,20405.0,20336.0,20410.0,20253.0,20027.0,...,21490.0,21361.0,21075.0,20769.0,20754.0,20529.0,20259.0,20159.0,20115.0,20098.0
08/07/2022,Low Carbon,8853.0,8750.0,8453.0,8391.0,8440.0,8318.0,8194.0,8231.0,8222.0,...,8860.0,8859.0,8925.0,8886.0,8771.0,8828.0,8843.0,8798.0,8680.0,8554.0
08/08/2022,Demand,27882.0,27868.0,27807.0,27669.0,27544.0,27360.0,27219.0,27085.0,26941.0,...,31856.0,31666.0,31435.0,31215.0,31009.0,30775.0,30572.0,30359.0,30165.0,29934.0
08/08/2022,High Carbon,20031.0,19956.0,19726.0,19642.0,19654.0,19586.0,19496.0,19397.0,19406.0,...,22536.0,22045.0,21589.0,21417.0,21288.0,21155.0,21170.0,21192.0,21069.0,21018.0
08/08/2022,Low Carbon,8460.0,8404.0,8453.0,8316.0,8226.0,8128.0,8101.0,8048.0,7911.0,...,8288.0,8455.0,8548.0,8478.0,8435.0,8372.0,8208.0,8145.0,8116.0,8017.0

# Include Imports Separately

In [214]:
demdf = pd.read_csv('CAISO-demand-2022.csv')
demdf.set_index('Date', inplace=True)
alldf = pd.read_csv('CAISO-allsupply-2022.csv')
alldf.set_index('Type', inplace=True)

In [215]:
imports=(alldf.loc[['Imports']]).set_index('Date')
highcarbon=(alldf.loc[['Biogas','Biomass','Coal','Natural gas','Other']]).groupby(['Date']).sum()
lowcarbon=(alldf.loc[['Batteries','Geothermal','Large hydro','Nuclear','Small hydro','Solar','Wind']]).groupby(['Date']).sum()

In [216]:
lowcarbon.insert(0, "Type", 'Low Carbon', True)
highcarbon.insert(0, "Type", 'High Carbon', True)
imports.insert(0,"Type", 'Imports', True)

In [217]:
result = pd.concat([lowcarbon,highcarbon,imports,demdf])
result.sort_values(by=['Date','Type'],ascending=[True,True],inplace=True)

result.to_csv("CAISO-ImportsInstate-2022.csv")

In [219]:
result

,Type,00:00,00:05,00:10,00:15,00:20,00:25,00:30,00:35,00:40,...,23:10,23:15,23:20,23:25,23:30,23:35,23:40,23:45,23:50,23:55
Date,,,,,,,,,,,,,,,,,,,,,
01/01/2022,Demand,22583.0,22496.0,22429.0,22350.0,22289.0,22198.0,22101.0,22019.0,21951.0,...,23333.0,23209.0,23088.0,22983.0,22893.0,22781.0,22670.0,22580.0,22500.0,22389.0
01/01/2022,High Carbon,7786.0,7626.0,7409.0,7374.0,7366.0,7374.0,7334.0,7420.0,7417.0,...,10516.0,10498.0,10358.0,10308.0,10340.0,10396.0,10423.0,10502.0,10476.0,10462.0
01/01/2022,Imports,8200.0,8079.0,8085.0,7962.0,7973.0,7889.0,7822.0,7890.0,7927.0,...,7814.0,7735.0,7811.0,7794.0,7674.0,7483.0,7400.0,7384.0,7218.0,7271.0
01/01/2022,Low Carbon,8173.0,8357.0,8453.0,8563.0,8508.0,8519.0,8495.0,8326.0,8287.0,...,5614.0,5651.0,5631.0,5706.0,5726.0,5733.0,5633.0,5546.0,5608.0,5477.0
01/02/2022,Demand,22583.0,22496.0,22429.0,22350.0,22289.0,22198.0,22101.0,22019.0,21951.0,...,23333.0,23209.0,23088.0,22983.0,22893.0,22781.0,22670.0,22580.0,22500.0,22389.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
08/07/2022,Low Carbon,8853.0,8750.0,8453.0,8391.0,8440.0,8318.0,8194.0,8231.0,8222.0,...,8860.0,8859.0,8925.0,8886.0,8771.0,8828.0,8843.0,8798.0,8680.0,8554.0
08/08/2022,Demand,27882.0,27868.0,27807.0,27669.0,27544.0,27360.0,27219.0,27085.0,26941.0,...,31856.0,31666.0,31435.0,31215.0,31009.0,30775.0,30572.0,30359.0,30165.0,29934.0
08/08/2022,High Carbon,12792.0,12849.0,12817.0,12803.0,12810.0,12757.0,12751.0,12723.0,12736.0,...,15832.0,15281.0,14952.0,14811.0,14689.0,14440.0,14432.0,14279.0,14163.0,14083.0
08/08/2022,Imports,7239.0,7107.0,6909.0,6839.0,6844.0,6829.0,6745.0,6674.0,6670.0,...,6704.0,6764.0,6637.0,6606.0,6599.0,6715.0,6738.0,6913.0,6906.0,6935.0
08/08/2022,Low Carbon,8460.0,8404.0,8453.0,8316.0,8226.0,8128.0,8101.0,8048.0,7911.0,...,8288.0,8455.0,8548.0,8478.0,8435.0,8372.0,8208.0,8145.0,8116.0,8017.0